version: 1.0.{build}
configuration:
- Debug
- Release
image:
- Visual Studio 2017
build:
  verbosity: normal
before_package:
- ps: Copy-Item C:\projects\XML\$env:CONFIGURATION\Motor 2D.exe C:\projects\XML\Game\.
artifacts:
- path: Game
  name: Release
